spring.application.name=leadforge
spring.main.allow-bean-definition-overriding=true
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/leadforge
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
jwt.secret=NTQxM2Q5MjZjNzM3YjFlYjJjMzZlN2VjYjljMzRkZTdjODcxZjYxY2Y2MjJjYzA2ZjllYWU1MGU3NDcwNDM0Nw
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=1209600000